// todo_react/src/TodoList.js
// src/TodoList.js
import React from 'react';
import Todo from './Todo';

function TodoList({ todos = [], toggleComplete, deleteTodo, updateTodo }) {
    return (
        <div id='list'>
            <ul>
                {todos.map(todo => (
                <Todo
                    key={todo.id}
                    todo={todo}
                    toggleComplete={toggleComplete}
                    deleteTodo={deleteTodo}
                    updateTodo={updateTodo}
                />
            ))}
            </ul>     
        </div>
    );
}

export default TodoList;

// todo_vue_using_pinia/src/components/TodoList.vue
<template>
  <div id="list">
    <ul>
        <TodoItem v-for="todo in todos" 
        :key="todo.id" :todo="todo"/>
    </ul>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { useTodoStore } from '../stores/todostore';
import TodoItem from './TodoItem.vue';

export default defineComponent({
  name: 'TodoList',
  components: {
    TodoItem,
  },setup() {
    const todoStore = useTodoStore();

    return {
      todos: todoStore.todos,
    };
  }
});
</script>
